[workspace]
resolver = "2"
members = [ "librazer", "razer-cli", "razer-tray"]

[profile.release]
lto = true
strip = true
codegen-units = 3

[profile.dev]
codegen-units = 1

[profile.test]
codegen-units = 1
