[workspace]
resolver = "2"
members = [ "librazer", "blade-helper"]

[workspace.package]
version = "0.7.1"

[profile.release]
lto = true
strip = true
codegen-units = 3

[profile.dev]
codegen-units = 1

[profile.test]
codegen-units = 1
